version: '3.8'

services:
  backend:
    build: ./backend
    container_name: meeting-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/meeting_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: meeting-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: meeting-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meeting_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data:
